#ifndef SM_SHARED_H
#define SM_SHARED_H

typedef enum state_e {
    SM_STATE_IDLE,
    SM_STATE_ERROR_BLINK,
    SM_STATE_INPUT_AWAIT,
    SM_STATE_ACCESS_GRANTED,
    SM_STATE_ACCESS_DENIED,
    SM_STATE_REQUEST_SID,
    SM_STATE_SEND_PIN
} state_e;

typedef enum state_event_e {
    SM_EVENT_BOOT,
    SM_EVENT_RFID_SCANNED,
    SM_EVENT_INPUT_TIMEOUT,
    SM_EVENT_PIN_INPUTTED,
    SM_EVENT_ERROR_BLINK_TIMEOUT,
    SM_EVENT_PROTOCOL_STATUS_TIMEOUT,
    SM_EVENT_PROTOCOL_STATUS_ERR,
    SM_EVENT_PROTOCOL_CMD_REQ_PIN,
    SM_EVENT_PROTOCOL_CMD_ERR,
    SM_EVENT_PROTOCOL_CMD_OK,
    SM_EVENT_PROTOCOL_CMD_UNEXPECTED,
    SM_EVENT_SESSION_EXPIRED,
} state_event_e;

typedef struct state_transition {
    state_e from;
    state_event_e event;
    state_e to;
} state_transition;

static const state_transition state_transitions[] = {
    { SM_STATE_IDLE, SM_EVENT_BOOT, SM_STATE_IDLE },
    { SM_STATE_IDLE, SM_EVENT_RFID_SCANNED, SM_STATE_REQUEST_SID },
    { SM_STATE_REQUEST_SID, SM_EVENT_PROTOCOL_CMD_REQ_PIN, SM_STATE_INPUT_AWAIT },
    { SM_STATE_REQUEST_SID, SM_EVENT_PROTOCOL_STATUS_TIMEOUT, SM_STATE_ERROR_BLINK },
    { SM_STATE_REQUEST_SID, SM_EVENT_PROTOCOL_STATUS_ERR, SM_STATE_ERROR_BLINK },
    { SM_STATE_REQUEST_SID, SM_EVENT_PROTOCOL_CMD_ERR, SM_STATE_ACCESS_DENIED },
    { SM_STATE_REQUEST_SID, SM_EVENT_PROTOCOL_CMD_UNEXPECTED, SM_STATE_ERROR_BLINK },
    { SM_STATE_INPUT_AWAIT, SM_EVENT_PIN_INPUTTED, SM_STATE_SEND_PIN },
    { SM_STATE_INPUT_AWAIT, SM_EVENT_INPUT_TIMEOUT, SM_STATE_ERROR_BLINK },
    { SM_STATE_SEND_PIN, SM_EVENT_PROTOCOL_CMD_OK, SM_STATE_ACCESS_GRANTED },
    { SM_STATE_SEND_PIN, SM_EVENT_PROTOCOL_CMD_ERR, SM_STATE_ACCESS_DENIED },
    { SM_STATE_SEND_PIN, SM_EVENT_PROTOCOL_STATUS_TIMEOUT, SM_STATE_ERROR_BLINK },
    { SM_STATE_SEND_PIN, SM_EVENT_PROTOCOL_STATUS_ERR, SM_STATE_ERROR_BLINK },
    { SM_STATE_ACCESS_GRANTED, SM_EVENT_SESSION_EXPIRED, SM_STATE_IDLE },
    { SM_STATE_ACCESS_DENIED, SM_EVENT_SESSION_EXPIRED, SM_STATE_IDLE },
    { SM_STATE_ERROR_BLINK, SM_EVENT_ERROR_BLINK_TIMEOUT, SM_STATE_IDLE },
};
#endif
